package ConnexionPackage;

/**
* ConnexionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 24 janvier 2017 09 h 21 CET
*/

public interface ConnexionOperations 
{
  String[] getClients ();
  void sendMessages (String from, String to, String message);
  String[] getMessages (String message);
  void connect (String pseudo);
  void disconnect (String pseudo);
} // interface ConnexionOperations
