package ConnexionPackage;

/**
* ConnexionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 24 janvier 2017 09 h 21 CET
*/

abstract public class ConnexionHelper
{
  private static String  _id = "IDL:Connexion:1.0";

  public static void insert (org.omg.CORBA.Any a, Connexion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Connexion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ConnexionHelper.id (), "Connexion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Connexion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConnexionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Connexion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Connexion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Connexion)
      return (Connexion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ConnexionStub stub = new _ConnexionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Connexion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Connexion)
      return (Connexion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ConnexionStub stub = new _ConnexionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
