package ConnexionPackage;

/**
* Connexion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 24 janvier 2017 09 h 21 CET
*/

public interface Connexion extends ConnexionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Connexion
