package ConnexionPackage;

/**
* ConnexionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 24 janvier 2017 09 h 21 CET
*/

public abstract class ConnexionPOA extends org.omg.PortableServer.Servant
 implements ConnexionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getClients", new java.lang.Integer (0));
    _methods.put ("sendMessages", new java.lang.Integer (1));
    _methods.put ("getMessages", new java.lang.Integer (2));
    _methods.put ("connect", new java.lang.Integer (3));
    _methods.put ("disconnect", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Connexion/getClients
       {
         String $result[] = null;
         $result = this.getClients ();
         out = $rh.createReply();
         ConnexionPackage.stringsHelper.write (out, $result);
         break;
       }

       case 1:  // Connexion/sendMessages
       {
         String from = in.read_string ();
         String to = in.read_string ();
         String message = in.read_string ();
         this.sendMessages (from, to, message);
         out = $rh.createReply();
         break;
       }

       case 2:  // Connexion/getMessages
       {
         String message = in.read_string ();
         String $result[] = null;
         $result = this.getMessages (message);
         out = $rh.createReply();
         ConnexionPackage.stringsHelper.write (out, $result);
         break;
       }

       case 3:  // Connexion/connect
       {
         String pseudo = in.read_string ();
         this.connect (pseudo);
         out = $rh.createReply();
         break;
       }

       case 4:  // Connexion/disconnect
       {
         String pseudo = in.read_string ();
         this.disconnect (pseudo);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Connexion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Connexion _this() 
  {
    return ConnexionHelper.narrow(
    super._this_object());
  }

  public Connexion _this(org.omg.CORBA.ORB orb) 
  {
    return ConnexionHelper.narrow(
    super._this_object(orb));
  }


} // class ConnexionPOA
